### ISSUE TITLE
docker出现频繁掉线问题

### ISSUE THREAD

**Issue by LCCC596** [EricZhou05/ESurfingDialerTutorial#5]
[dialer.log](https://github.com/user-attachments/files/17948968/dialer.log)
主路由是X86的openwrt 下级接了个tp的路由器给宿友共享，貌似是有设备把宽带跑满了就会出现这个问题，之后我进行了设备限速（不超过校园网宽带）好了几天之后依旧出现此问题
![20241128215535](https://github.com/user-attachments/assets/1a062a81-f910-4470-a2ca-4b8a0d6d4583)

**Comment by EricZhou05** [comment]
主分支重复issues，关闭了
[issues](https://github.com/Rsplwe/ESurfingDialer/issues/78)
